In [1]:

import sys
sys.path.append("../../")

from biked_commons.design_evaluation.design_evaluation import *
from biked_commons.conditioning import conditioning
from biked_commons.resource_utils import split_datasets_path
from biked_commons.benchmark_models import benchmarking_utils

In [ ]:
import importlib
importlib.reload(benchmarking_utils)
scores = benchmarking_utils.create_score_report_conditional()
#turn constraint satisfaction rate into a percent with two decimal places
scores['Constraint Satisfaction Rate'] = scores['Constraint Satisfaction Rate'] * 100
scores['Constraint Satisfaction Rate'] = scores['Constraint Satisfaction Rate'].apply(lambda x: "{:.2f}%".format(x))

#four decimals for Hypervolume and Maximum Mean Discrepancy
scores['Hypervolume'] = scores['Hypervolume'].apply(lambda x: "{:.4f}".format(x))
scores['Maximum Mean Discrepancy'] = scores['Maximum Mean Discrepancy'].apply(lambda x: "{:.4f}".format(x))


savedir = os.path.join("results", "cond_overall_scores.csv")
scores.to_csv(savedir, index=False)
display(scores)

,Constraint Satisfaction Rate,Hypervolume,Maximum Mean Discrepancy
CTGAN,0.87%,0.4090,0.0324
DDPM_conditional-PA,40.46%,0.3801,0.0590
DDPM_guided-PA,3.24%,0.2925,0.0337
Dataset,2.75%,0.4151,0.0000
GAN-PA,22.34%,0.4152,0.1791
O4-mini,0.63%,0.2615,0.3460
TVAE,0.00%,0.0000,0.0365
VAE-PA,81.65%,0.4357,0.0693

In [ ]:
scores = benchmarking_utils.create_score_report_unconditional()
#turn constraint satisfaction rate into a percent with two decimal places
scores['Constraint Satisfaction Rate'] = scores['Constraint Satisfaction Rate'] * 100
scores['Constraint Satisfaction Rate'] = scores['Constraint Satisfaction Rate'].apply(lambda x: "{:.2f}%".format(x))

#four decimals for Hypervolume and Maximum Mean Discrepancy
scores['Hypervolume'] = scores['Hypervolume'].apply(lambda x: "{:.4f}".format(x))
scores['Maximum Mean Discrepancy'] = scores['Maximum Mean Discrepancy'].apply(lambda x: "{:.4f}".format(x))

savedir = os.path.join("results", "uncond_overall_scores.csv")
scores.to_csv(savedir, index=False)
display(scores)

,Constraint Satisfaction Rate,Hypervolume,Maximum Mean Discrepancy
Agg-LS,98.55%,0.3648,0.3824
CTGAN,0.58%,0.1496,0.0252
DDPM_conditional-PA,54.24%,0.2750,0.0740
Dataset,2.70%,0.2428,0.0006
EPO,92.00%,0.2625,0.2286
GAN-PA,24.16%,0.3228,0.1066
NSGA2,100.00%,0.4293,0.5051
O4-mini,0.28%,0.0115,0.5026
TVAE,0.05%,0.0334,0.0400
VAE-PA,80.55%,0.2712,0.1081