In [1]:
import pandas as pd
import torch
import numpy as np
import sys

sys.path.append("../../")
import biked_commons
from biked_commons.resource_utils import split_datasets_path
from biked_commons.transformation import framed, one_hot_encoding
from biked_commons.prediction import loaders

In [2]:
p = split_datasets_path('bike_bench_mixed_modality.csv')
data = pd.read_csv(p, index_col=0)

In [3]:
data

,CS textfield,BB textfield,Stack,Head angle,Head tube length textfield,Seat stay junction0,Seat tube length,Seat angle,DT Length,FORK0R,...,RIM_STYLE rear,SPOKES composite front,SPOKES composite rear,SBLADEW front,SBLADEW rear,Saddle length,Saddle height,Down tube diameter,Seatpost LENGTH,Seat tube type
1,430.00,67.000000,608.323843,73.000000,135.6,45.0,588.7,72.500000,659.334805,45.0,...,SPOKED,1,1,80.0,80.0,298.0,768.0,34.9,300.0,2
2,350.00,-14.500000,476.785508,71.500000,80.0,45.0,265.0,71.500000,572.243339,45.0,...,SPOKED,1,1,80.0,80.0,240.0,330.0,40.0,100.0,1
3,415.00,4.000000,578.316581,72.000000,198.8,45.0,562.0,74.000000,647.085192,35.0,...,SPOKED,1,1,80.0,80.0,278.0,763.0,35.0,300.0,1
4,375.00,50.000000,480.254885,70.500000,91.8,40.0,460.0,73.500000,570.880683,45.0,...,SPOKED,1,1,80.0,80.0,298.0,600.0,28.6,140.0,1
5,431.79,24.000000,504.207465,72.100000,83.1,41.0,300.0,72.500000,635.549712,45.0,...,SPOKED,1,1,80.0,80.0,210.0,350.0,45.0,250.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,410.00,75.000000,589.233160,72.500000,145.0,125.0,520.0,74.000000,638.393570,45.0,...,SPOKED,1,1,80.0,80.0,275.0,710.0,50.0,320.0,1
4797,419.00,42.909345,519.159903,65.772099,95.0,90.0,380.0,77.772099,702.453382,45.0,...,SPOKED,1,1,80.0,80.0,278.0,720.0,38.0,465.0,1
4798,410.00,-11.500000,498.857266,72.000000,250.0,45.0,550.0,74.000000,547.749388,45.0,...,TRISPOKE,3,3,40.0,40.0,298.0,740.0,34.9,330.0,1
4799,410.00,-11.500000,527.769384,72.000000,280.4,45.0,550.0,74.000532,542.196571,45.0,...,SPOKED,3,3,40.0,40.0,298.0,740.0,34.9,330.0,1
4800,440.00,64.500000,594.468055,73.500000,145.7,45.0,584.3,73.500000,654.992964,45.0,...,SPOKED,1,1,80.0,80.0,298.0,775.0,34.9,330.0,1

In [4]:
# roh = one_hot_encoding.reverse_one_hot_encoding(data)

In [5]:
res = one_hot_encoding.encode_to_continuous(data)

In [6]:
res

,CS textfield,BB textfield,Stack,Head angle,Head tube length textfield,Seat stay junction0,Seat tube length,Seat angle,DT Length,FORK0R,...,Handlebar style OHCLASS: 2,Stem kind OHCLASS: 0,Stem kind OHCLASS: 1,Stem kind OHCLASS: 2,Fork type OHCLASS: 0,Fork type OHCLASS: 1,Fork type OHCLASS: 2,Seat tube type OHCLASS: 0,Seat tube type OHCLASS: 1,Seat tube type OHCLASS: 2
1,430.00,67.000000,608.323843,73.000000,135.6,45.0,588.7,72.500000,659.334805,45.0,...,0,1,0,0,1,0,0,0,0,1
2,350.00,-14.500000,476.785508,71.500000,80.0,45.0,265.0,71.500000,572.243339,45.0,...,0,1,0,0,0,1,0,0,1,0
3,415.00,4.000000,578.316581,72.000000,198.8,45.0,562.0,74.000000,647.085192,35.0,...,0,1,0,0,1,0,0,0,1,0
4,375.00,50.000000,480.254885,70.500000,91.8,40.0,460.0,73.500000,570.880683,45.0,...,0,1,0,0,1,0,0,0,1,0
5,431.79,24.000000,504.207465,72.100000,83.1,41.0,300.0,72.500000,635.549712,45.0,...,0,1,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,410.00,75.000000,589.233160,72.500000,145.0,125.0,520.0,74.000000,638.393570,45.0,...,0,1,0,0,1,0,0,0,1,0
4797,419.00,42.909345,519.159903,65.772099,95.0,90.0,380.0,77.772099,702.453382,45.0,...,0,1,0,0,0,1,0,0,1,0
4798,410.00,-11.500000,498.857266,72.000000,250.0,45.0,550.0,74.000000,547.749388,45.0,...,0,1,0,0,1,0,0,0,1,0
4799,410.00,-11.500000,527.769384,72.000000,280.4,45.0,550.0,74.000532,542.196571,45.0,...,0,1,0,0,1,0,0,0,1,0
4800,440.00,64.500000,594.468055,73.500000,145.7,45.0,584.3,73.500000,654.992964,45.0,...,0,0,1,0,1,0,0,0,1,0

In [7]:
recat = one_hot_encoding.decode_to_mixed(res)
recat

,CS textfield,BB textfield,Stack,Head angle,Head tube length textfield,Seat stay junction0,Seat tube length,Seat angle,DT Length,FORK0R,...,Seatpost LENGTH,MATERIAL,Dropout spacing style,Head tube type,RIM_STYLE front,RIM_STYLE rear,Handlebar style,Stem kind,Fork type,Seat tube type
1,430.00,67.000000,608.323843,73.000000,135.6,45.0,588.7,72.500000,659.334805,45.0,...,300.0,STEEL,2,1,SPOKED,SPOKED,0,0,0,2
2,350.00,-14.500000,476.785508,71.500000,80.0,45.0,265.0,71.500000,572.243339,45.0,...,100.0,ALUMINIUM,1,1,SPOKED,SPOKED,1,0,1,1
3,415.00,4.000000,578.316581,72.000000,198.8,45.0,562.0,74.000000,647.085192,35.0,...,300.0,STEEL,1,1,SPOKED,SPOKED,1,0,0,1
4,375.00,50.000000,480.254885,70.500000,91.8,40.0,460.0,73.500000,570.880683,45.0,...,140.0,STEEL,2,1,SPOKED,SPOKED,0,0,0,1
5,431.79,24.000000,504.207465,72.100000,83.1,41.0,300.0,72.500000,635.549712,45.0,...,250.0,STEEL,1,1,SPOKED,SPOKED,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,410.00,75.000000,589.233160,72.500000,145.0,125.0,520.0,74.000000,638.393570,45.0,...,320.0,STEEL,0,1,SPOKED,SPOKED,1,0,0,1
4797,419.00,42.909345,519.159903,65.772099,95.0,90.0,380.0,77.772099,702.453382,45.0,...,465.0,STEEL,0,3,SPOKED,SPOKED,1,0,1,1
4798,410.00,-11.500000,498.857266,72.000000,250.0,45.0,550.0,74.000000,547.749388,45.0,...,330.0,STEEL,2,1,TRISPOKE,TRISPOKE,0,0,0,1
4799,410.00,-11.500000,527.769384,72.000000,280.4,45.0,550.0,74.000532,542.196571,45.0,...,330.0,STEEL,2,1,TRISPOKE,SPOKED,0,0,0,1
4800,440.00,64.500000,594.468055,73.500000,145.7,45.0,584.3,73.500000,654.992964,45.0,...,330.0,STEEL,2,1,SPOKED,SPOKED,0,1,0,1

In [16]:
print(data["Stem kind"])
print(recat["Stem kind"])

1       0
2       0
3       0
4       0
5       0
       ..
4796    0
4797    0
4798    0
4799    0
4800    1
Name: Stem kind, Length: 4512, dtype: int64
1       0
2       0
3       0
4       0
5       0
       ..
4796    0
4797    0
4798    0
4799    0
4800    1
Name: Stem kind, Length: 4512, dtype: object

In [9]:
#check if the original and the recat are the same

for i in data.columns:
    if i in recat.columns:
        if not np.array_equal(data[i].values, recat[i].values):
            print(f"Column {i} is not the same")
    else:
        print(f"Column {i} is missing in recat")

Column DT Length is not the same
Column Dropout spacing style is not the same
Column Fork type is not the same
Column Stem kind is not the same
Column Handlebar style is not the same
Column Head tube type is not the same
Column Seat tube type is not the same

In [ ]:
import importlib
importlib.reload(framed)

# res = framed.clip_to_framed(clip)

converter = framed.clip_to_framed_tensor_builder(clip.columns, f.columns)

In [4]:
clip_tens = torch.tensor(clip.values, dtype=torch.float32)
res = converter(clip_tens)

In [6]:
f.values

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.34500000e-03, 6.20600000e-03, 6.60599000e-01],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        8.72000000e-04, 3.57300000e-03, 6.74965000e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.05400000e-03, 4.00300000e-03, 5.68519000e-01],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.19047437e-03, 2.93954573e-03, 5.70119304e-01],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        3.29700000e-03, 3.79900000e-03, 6.45932000e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        2.13771839e-03, 1.28586292e-03, 6.68856383e-01]])

In [62]:
#check if f[0] and res[0] are the same, but with different column orders

f = f.reindex(sorted(f.columns), axis=1)
res = res.reindex(sorted(res.columns), axis=1)

#get differences between first rows of f and res
diff = f.iloc[0] != res.iloc[0]
diff = diff[diff].index.tolist()

ValueError: Can only compare identically-labeled Series objects