In [1]:
import pandas as pd
import torch
import numpy as np
import sys

sys.path.append("../../")
import biked_commons
from biked_commons.resource_utils import split_datasets_path
from biked_commons.transformation import framed
from biked_commons.prediction import loaders

In [17]:
p = split_datasets_path('CLIP_X_test.csv')
clip = pd.read_csv(p, index_col=0)
f, _ = loaders.load_validity()

In [29]:
f.columns

Index(['Material=Steel', 'Material=Aluminum', 'Material=Titanium',
       'SSB_Include', 'CSB_Include', 'CS Length', 'BB Drop', 'Stack', 'SS E',
       'ST Angle', 'BB OD', 'TT OD', 'HT OD', 'DT OD', 'CS OD', 'SS OD',
       'ST OD', 'CS F', 'HT LX', 'ST UX', 'HT UX', 'HT Angle', 'HT Length',
       'ST Length', 'BB Length', 'Dropout Offset', 'SSB OD', 'CSB OD',
       'SSB Offset', 'CSB Offset', 'SS Z', 'SS Thickness', 'CS Thickness',
       'TT Thickness', 'BB Thickness', 'HT Thickness', 'ST Thickness',
       'DT Thickness', 'DT Length'],
      dtype='object')

In [18]:
clip

,CS textfield,BB textfield,Stack,Head angle,Head tube length textfield,Seat stay junction0,Seat tube length,Seat angle,DT Length,BB diameter,...,bottle DOWNTUBE0 show OHCLASS: False,bottle DOWNTUBE0 show OHCLASS: True,BELTorCHAIN OHCLASS: 0,BELTorCHAIN OHCLASS: 1,RIM_STYLE front OHCLASS: DISC,RIM_STYLE front OHCLASS: SPOKED,RIM_STYLE front OHCLASS: TRISPOKE,RIM_STYLE rear OHCLASS: DISC,RIM_STYLE rear OHCLASS: SPOKED,RIM_STYLE rear OHCLASS: TRISPOKE
1,430.00,67.000000,565.6,73.000000,135.6,45.0,588.7,72.500000,664.020690,40.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,350.00,-14.500000,565.6,71.500000,80.0,45.0,265.0,71.500000,572.491950,40.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
3,415.00,4.000000,565.6,72.000000,198.8,45.0,562.0,74.000000,647.103654,38.1,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4,375.00,50.000000,565.6,70.500000,91.8,40.0,460.0,73.500000,573.904093,38.1,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
5,431.79,24.000000,565.6,72.100000,83.1,41.0,300.0,72.500000,636.179297,40.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,410.00,75.000000,552.0,72.500000,145.0,125.0,520.0,74.000000,644.551458,40.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4797,419.00,42.909345,598.9,65.772099,95.0,90.0,380.0,77.772099,704.278730,40.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4798,410.00,-11.500000,492.5,72.000000,250.0,45.0,550.0,74.000000,547.934671,40.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
4799,410.00,-11.500000,500.0,72.000000,280.4,45.0,550.0,74.000532,542.387502,40.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4800,440.00,64.500000,565.6,73.500000,145.7,45.0,584.3,73.500000,659.573115,40.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0

In [ ]:
f[]

,Material=Steel,Material=Aluminum,Material=Titanium,SSB_Include,CSB_Include,CS Length,BB Drop,Stack,SS E,ST Angle,...,CSB Offset,SS Z,SS Thickness,CS Thickness,TT Thickness,BB Thickness,HT Thickness,ST Thickness,DT Thickness,DT Length
9237,1,0,0,0.0,0.0,0.454210,4.974500e-02,0.56541,0.028226,74.602428,...,0.381567,0.010334,0.006401,0.001903,0.003043,0.003054,0.008850,0.002345,0.006206,0.660599
8922,1,0,0,1.0,1.0,0.428072,7.297700e-02,0.56664,0.034613,72.058553,...,0.299777,0.008548,0.006327,0.002624,0.002506,0.000540,0.002825,0.000872,0.003573,0.674965
11585,0,1,0,1.0,1.0,0.358010,-2.328000e-02,0.55498,0.175450,74.661000,...,0.349621,0.008206,0.003124,0.006949,0.000855,0.005617,0.001092,0.001054,0.004003,0.568519
6892,0,0,1,1.0,1.0,0.404602,7.005700e-02,0.56557,0.044059,74.011709,...,0.350116,0.008996,0.001073,0.001192,0.000751,0.000813,0.000962,0.000798,0.000956,0.658852
4783,0,1,0,1.0,1.0,0.297080,-1.282000e-02,0.56564,0.053940,66.369610,...,0.300662,0.009216,0.001014,0.001998,0.001276,0.000651,0.008124,0.008348,0.005268,0.415527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7997,1,0,0,0.0,0.0,0.425420,2.526700e-02,0.56560,0.045000,72.488558,...,0.300000,0.009000,0.003461,0.001703,0.003410,0.001102,0.004535,0.002055,0.009791,0.674373
13948,1,0,0,0.0,0.0,0.409670,5.098800e-02,0.56523,0.039210,73.530997,...,0.290824,0.008977,0.002399,0.002827,0.005921,0.002497,0.003042,0.006572,0.002998,0.665984
1307,1,0,0,0.0,0.0,0.362440,1.989520e-15,0.56560,0.045000,74.000000,...,0.300000,0.009000,0.002200,0.002957,0.001814,0.000863,0.001952,0.003190,0.002940,0.570119
8870,0,0,1,1.0,1.0,0.392032,6.675600e-02,0.53600,0.173262,75.240875,...,0.349996,0.008863,0.001042,0.000980,0.003368,0.003429,0.001838,0.003297,0.003799,0.645932
3414,0,1,0,1.0,1.0,0.408000,6.700000e-02,0.59300,0.045000,73.500000,...,0.350000,0.009000,0.002069,0.009264,0.000980,0.001046,0.002093,0.002138,0.001286,0.668856

In [25]:
f.loc[1]

Material=Steel        0.000000
Material=Aluminum     1.000000
Material=Titanium     0.000000
SSB_Include           0.000000
CSB_Include           0.000000
CS Length             0.350000
BB Drop              -0.014500
Stack                 0.565600
SS E                  0.045000
ST Angle             71.500000
BB OD                 0.040000
TT OD                 0.029200
HT OD                 0.045000
DT OD                 0.036500
CS OD                 0.022000
SS OD                 0.018500
ST OD                 0.031800
CS F                  0.015000
HT LX                 0.023100
ST UX                 0.039100
HT UX                 0.023300
HT Angle             71.500000
HT Length             0.080000
ST Length             0.265000
BB Length             0.068000
Dropout Offset        0.135000
SSB OD                0.015843
CSB OD                0.017746
SSB Offset            0.330000
CSB Offset            0.350000
SS Z                  0.008000
SS Thickness          0.008671
CS Thickness          0.001011
TT Thickness          0.005782
BB Thickness          0.000721
HT Thickness          0.003873
ST Thickness          0.000913
DT Thickness          0.008889
DT Length             0.572492
Name: 1, dtype: float64

In [ ]:
import importlib
importlib.reload(framed)

# res = framed.clip_to_framed(clip)

converter = framed.clip_to_framed_tensor_builder(clip.columns, f.columns)

In [4]:
clip_tens = torch.tensor(clip.values, dtype=torch.float32)
res = converter(clip_tens)

In [6]:
f.values

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.34500000e-03, 6.20600000e-03, 6.60599000e-01],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        8.72000000e-04, 3.57300000e-03, 6.74965000e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.05400000e-03, 4.00300000e-03, 5.68519000e-01],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        3.19047437e-03, 2.93954573e-03, 5.70119304e-01],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        3.29700000e-03, 3.79900000e-03, 6.45932000e-01],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        2.13771839e-03, 1.28586292e-03, 6.68856383e-01]])

In [62]:
#check if f[0] and res[0] are the same, but with different column orders

f = f.reindex(sorted(f.columns), axis=1)
res = res.reindex(sorted(res.columns), axis=1)

#get differences between first rows of f and res
diff = f.iloc[0] != res.iloc[0]
diff = diff[diff].index.tolist()

ValueError: Can only compare identically-labeled Series objects